language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="cviode:. owl-ode:https://github.com/owlbarn/owl_ode/archive/master.tar.gz owl:https://github.com/mseri/owl/archive/owl-cleanup-configure-part1.tar.gz owl-aeos:https://github.com/mseri/owl/archive/owl-cleanup-configure-part1.tar.gz owl-base:https://github.com/mseri/owl/archive/owl-cleanup-configure-part1.tar.gz owl-plplot:https://github.com/owlbarn/owl/archive/master.tar.gz"
  matrix:
  - PACKAGE="cviode" DISTRO="debian-stable" OCAML_VERSION="4.07"
  - PACKAGE="cviode" DISTRO="debian-stable" OCAML_VERSION="4.06"
